language: csharp
dist: xenial
env:
  global:
    - Configuration=Release
    - ASPNETCORE_ENVIRONMENT=Staging
dotnet: 5.0.0
mono: none
branches:
  only:
  - master
  - /^release\/.*$/
  - develop
before_install:
  - chmod +x build.sh
script:
  - dotnet --info
  - ./build.sh -target=sonar
