version: '{build}'
image:
- Visual Studio 2017
- Ubuntu
configuration: Release

cache:
  - tools -> build.cake
  - packages -> **\packages.config, nuget.config

environment:
  ASPNETCORE_ENVIRONMENT: Staging
  COREHOST_TRACE: 0
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

nuget:
  project_feed: true
  disable_publish_on_pr: true

artifacts:
- path: build\artifacts\*.nupkg

deploy: off
branches:
  only:
    - develop
    - /release.*/ 
    - master
skip_commits:
  files:
  - LICENSE
  - README.md
  - .travis.yml

for:
  -
    matrix:
      only:
      - image: Visual Studio 2017
    before_build:
      - choco install dotnetcore-sdk --version 2.2.203
      - choco install codecov    
    build_script:
      - ps: >-
          .\build.ps1 
        
  -
    matrix:
      only:
        - image: Ubuntu
    before_build:
      - export PATH="$PATH:/home/appveyor/.dotnet/tools"
      - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
      - sudo dpkg -i packages-microsoft-prod.deb
      - sudo apt-get install apt-transport-https
      - sudo apt-get update
      - sudo apt-get install dotnet-sdk-2.2 -y
      - dotnet --info
      - dotnet tool install -g Cake.Tool
      - dotnet tool list -g 
      - chmod +x build.sh
    build_script:
      - ./build.sh
