trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature*
  paths:
    exclude:
    - infastructure/*

variables:
  buildConfiguration: 'Release'

jobs:

- job: Linux 
  
  pool:
    vmImage: 'ubuntu-16.04'
  
  variables:
  - group: 'Docker Hub'
  
  steps:

  - script: |
      ./build.sh --target=CI-Build
    displayName: 'Cake Build'
  
  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '.test-results\*.trx'
  
  - script: |
      docker login -u $(dockerLogin) -p $(dockerPassword)
      docker build -f docker/azuredevopskats-web-local.dockerfile/Dockerfile -t stuartshay/azuredevopskats:devops  .
      docker push stuartshay/azuredevopskats:devops 
    displayName: 'Docker Build & Push'
    env:
      COREHOST_TRACE: 0
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1


