trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature*
  paths:
    exclude:
    - infastructure/*

variables:
  buildConfiguration: 'Release'

jobs:

- job: Windows
  pool: 
    vmImage: 'windows-2019'
  steps:
    
  - powershell: |
      .\build.ps1
  - task: CopyFiles@2
    inputs:
       contents: 'artifacts\**'
       targetFolder: $(Build.ArtifactStagingDirectory)

 