trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature*
  paths:
    exclude:
    - infastructure/*

variables:
  buildConfiguration: 'Release'

jobs:

- job: Windows
  pool: 
    vmImage: 'windows-2019'
  steps:

  - task: DotNetCoreInstaller@0
    inputs:
     version: '2.2.203'  

  - task: Cake@0
    inputs:
     script: 'build.cake'
     target: 'CI-Build'
     verbosity: 'Verbose'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '.test-results\*.trx'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'cobertura-coverage.xml'

  - task: CopyFiles@2
    inputs:
       contents: 'publish\Release\**'
       targetFolder: $(Build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    inputs:
     pathtoPublish: $(Build.ArtifactStagingDirectory)
     artifactName: WebApplicationBundle

  - task: GitHubPagesPublish@1
    inputs:
      docPath: 'docFx\*'
      githubusername: 'stuartshay'
      githubemail: 'sshay@yahoo.com'
      githubaccesstoken: '12593d2a799c8e06fac69171f91b93fd1ca0341d'
      repositoryname: 'AzureDevOpsKats'
      branchname: 'gh-pages'
      commitmessage: 'Automated Release $(Release.ReleaseId)'


