trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature*
  paths:
    exclude:
    - infastructure/*

variables:
  buildConfiguration: 'Release'

jobs:

- job: Windows
  pool: 
    vmImage: 'windows-2019'
  steps:

  - task: DotNetCoreInstaller@0
    inputs:
     version: '2.2.203'  

  - powershell: |
      .\build.ps1 --target=test 
  
  - task: CopyFiles@2
    inputs:
       contents: '.test-results\**'
       targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '.test-results\*.trx'
  

 