trigger:
  branches:
    include:
    - master
    - develop
    - releases/*
    - feature*
  paths:
    exclude:
    - infastructure/*

variables:
  buildConfiguration: 'Release'

jobs:

- job: Windows
  variables:
  - group: 'Git Hub'
  
  pool: 
    vmImage: 'windows-2019'
  steps:

  - task: PowerShell@2
    inputs:
     targetType: 'inline'
     script: 'Write-Host "Hello World"
     Write-Host "$(git_username)"'

  - task: DotNetCoreInstaller@0
    inputs:
     version: '2.2.203'  

  - task: Cake@0
    inputs:
     script: 'build.cake'
     target: 'CI-Build'
     verbosity: 'Verbose'

  - task: PublishTestResults@2
    inputs:
      testRunner: VSTest
      testResultsFiles: '.test-results\*.trx'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: 'cobertura-coverage.xml'

  - task: CopyFiles@2
    inputs:
       contents: 'publish\Release\**'
       targetFolder: $(Build.ArtifactStagingDirectory)
  
  - task: PublishBuildArtifacts@1
    inputs:
     pathtoPublish: $(Build.ArtifactStagingDirectory)
     artifactName: WebApplicationBundle



