version: "3.7"

services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:9.2.4-community
    ports:
      - "9000:9000"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    networks:
      - sonarnet

  db:
    container_name: sonardb
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

networks:
  sonarnet:

    null
