version: '3.8'

services:

  traefik:
    image: "traefik:v2.3"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80" 
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
     - azuredevopskats-network  

  azuredevopskats-web:
    hostname: azuredevopskats-web
    image: "stuartshay/azuredevopskats:5.0.1-build.17"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.azuredevopskats-web.rule=Host(`azuredevopskats-web`)"
      - "traefik.http.routers.azuredevopskats-web.entrypoints=web"   
    depends_on:
     - redis 
    networks:
     - azuredevopskats-network

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
    networks:
      - azuredevopskats-network

volumes:
  redis-data:

networks:
  azuredevopskats-network: