version: '3.8'

services:

  web-develop:
    hostname: web-develop
    image: "stuartshay/azuredevopskats:5.0.1-build.12"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports:
     - "5600:5000"
    networks:
      - azuredevopskats-network

networks:
  azuredevopskats-network:

