version: '3.8'

services:

  web:
    hostname: web
    image: "stuartshay/azuredevopskats:5.0.1-arm.14"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports:
     - "5500:5000"
    networks:
      - azuredevopskats-network

networks:
  azuredevopskats-network:

