version: '3.8'

services:

  web-develop:
    hostname: web-develop
    image: "stuartshay/azuredevopskats:5.0.1-build.12"
    environment:
     - ASPNETCORE_ENVIRONMENT=Docker
    ports:
     - "5600:5000"
    networks:
      - azuredevopskats-network

  redis:
    image: bitnami/redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis-data:/data
    networks:
      - azuredevopskats-network


volumes:
  redis-data:

networks:
  azuredevopskats-network:

