heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://es01:9200
    - http://kib01:5601
    - http://azuredevopskats-web:5000/health
  #ssl:
  #  certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

- type: icmp
  schedule: '@every 5s'
  hosts:
    - es01
    - kib01

processors:
- add_cloud_metadata:


output.elasticsearch:
  hosts: ['es01:9200']
  protocol: "http"
  #username: elastic
  # Read PW from heartbeat.keystore
  #password: "${ELASTIC_PASSWORD}"
  #ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http:/kib01:5601"
  #username: elastic
  #password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  #ssl.certificate_authorities: ["/usr/share/heartbeat/certs/ca/ca.crt"]

xpack.monitoring.enabled: true