---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azuredevopskats
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: azuredevopskats
    spec:
      containers:
        - name: azuredevopskats
          image: stuartshay/azuredevopskats:devops
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: azuredevopskats-service
spec:
  type: LoadBalancer
  ports:
  - port: 5000
  selector:
    app: azuredevopskats
