name: AWS ECR Deploy

on:
  workflow_dispatch:
  push:
   paths:
      - 'src/**'
      - 'test/**'
      - '.github/workflows/aws.yml'
   branches:
      - master
      - develop
      - 'feature/**'
      - 'fix/**'

jobs:

  test-aws:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_AZUREKATS }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_AZUREKATS }}
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


